### ISSUE TITLE
Not all metrics being reported

### ISSUE THREAD

**Issue by gabricc** [sj26/sidekiq-cloudwatchmetrics#40]
Hey @sj26 ! Hope you are doing great!

Apparently not all of the sidekiq metrics are being sent to CloudWatch. I see that some queues are always zeroed:
![image](https://github.com/sj26/sidekiq-cloudwatchmetrics/assets/42014588/17829879-1733-411c-bc8f-8ace83a4e9ab)
While in the logs I see that sidekiq is processing the messages:
![image](https://github.com/sj26/sidekiq-cloudwatchmetrics/assets/42014588/02885ea8-b84f-499c-96f8-b37f7e1aa953)

The weird thing is that from the logs everything is fine:
`2023-08-04T19:12:15.412Z pid=1 tid=39d1 INFO: Publishing Sidekiq CloudWatch Metrics`
and metrics for some other queues are being properly sent to CloudWatch, it's like if it was working intermittently. 

These are the versions we are using:
    `sidekiq (6.3.1)`
    `sidekiq-cloudwatchmetrics (2.5.0)`
    
This is how we are initilizing the gem:
```
require "sidekiq"
require "sidekiq/cloudwatchmetrics"
Sidekiq::CloudWatchMetrics.enable!(namespace: "Sidekiq-" + ENV["ENVIRONMENT"])
```

Can you help to identify what might be happening? 🙏🏻 
Thanks and let me know if you need any additional info!

**Comment by sj26** [comment]
Hiya! Sorry, I'm not sure what might be going on there. We use this gem in production and don't have this issue, and this is the first report I've seen.

It looks like you're namespacing the metrics. Is `ENV["ENVIRONMENT"]` always reliably set? Are you seeing metrics in a `Sidekiq-/` namespace, or other namespaces?

**Comment by gabricc** [comment]
Hey @sj26 ! Yes, the variable is always reliably set!

But I think I found out what is happening, the messages are not even being queued because the consumers are picking them up right way, so they almost never get enqueued, only when there is a huuge spike of messages.
So I should be looking for a different metric, like `messagesProcessed` instead of `queueSize`.

I saw that your gem exports the `ProcessedJobs` metric, but it has no dimensions, so it's not possible to group by queue or job, do you think it's possible to add dimensions to it?

Thanks!!

**Comment by sj26** [comment]
Ah! Yeah, that'll do it. Statistics, hey 🤷🏻 

> I saw that your gem exports the `ProcessedJobs` metric, but it has no dimensions, so it's not possible to group by queue or job. Do you think it would be possible to add dimensions to it?

I'm just slurping up what Sidekiq has available and pushing it to CloudWatch with the same dimensions etc:

https://github.com/sj26/sidekiq-cloudwatchmetrics/blob/811240f0cae39b55cddb2ad26627f4164c334bae/lib/sidekiq/cloudwatchmetrics.rb#L97

I think that metric is system-wide, and does not have those dimensions, sadly.

**Comment by gabricc** [comment]
that makes total sense, thanks @sj26 !
