### ISSUE TITLE
Sidekiq 4 compatibility 

### ISSUE THREAD

**Issue by louman** [sj26/sidekiq-cloudwatchmetrics#5]
Hi there, any reason for making this gem sidekiq 5 only? It looks like you're not really using any 5-only features. Would you consider relaxing the dependency?

**Comment by sj26** [comment]
No real reason, just what we were using. Happy to relax the restriction if you can prove it works okay. :-)

**Comment by sj26** [comment]
I'm going to close this due to lack of activity.
